# Matrix Operations

In [1]:
import numpy

In [5]:
# Two matrices are initialized by value
x = numpy.matrix([[12, 45], [24, 65]])
y = numpy.matrix([[27, 72], [79, 16]])

In [6]:
#  add()is used to add matrices
print ("Addition of two matrices: ")
print (numpy.add(x,y))

Addition of two matrices: 
[[ 39 117]
 [103  81]]


In [7]:
# subtract()is used to subtract matrices
print ("Subtraction of two matrices : ")
print (numpy.subtract(x,y))

Subtraction of two matrices : 
[[-15 -27]
 [-55  49]]


In [8]:
# divide()is used to divide matrices
print ("Matrix Division : ")
print (numpy.divide(x,y))

Matrix Division : 
[[0.44444444 0.625     ]
 [0.30379747 4.0625    ]]


In [9]:
print ("Multiplication of two matrices: ")
print (numpy.multiply(x,y))

Multiplication of two matrices: 
[[ 324 3240]
 [1896 1040]]


In [10]:
print ("The product of two matrices : ")
print (numpy.dot(x,y))

The product of two matrices : 
[[3879 1584]
 [5783 2768]]


In [11]:
print ("square root is : ")
print (numpy.sqrt(x))

square root is : 
[[3.46410162 6.70820393]
 [4.89897949 8.06225775]]


In [12]:
print ("The summation of elements : ")
print (numpy.sum(y))

The summation of elements : 
194


In [13]:
print ("The column wise summation  : ")
print (numpy.sum(y,axis=0))

The column wise summation  : 
[[106  88]]


In [14]:
print ("The row wise summation: ")
print (numpy.sum(y,axis=1))

The row wise summation: 
[[99]
 [95]]


In [15]:
# using "T" to transpose the matrix
print ("Matrix transposition : ")
print (x.T)

Matrix transposition : 
[[12 24]
 [45 65]]


In [16]:
print ("Matrix Inverse : ")
print (x.I)

Matrix Inverse : 
[[-0.21666667  0.15      ]
 [ 0.08       -0.04      ]]
